ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 8080
    watch:
      - classes
      - resources
  development: $KTOR_DEVELOPMENT
line:
  channel:
    secret: $LINE_CHANNEL_SECRET
    token: $LINE_CHANNEL_TOKEN
