ktor:
  application:
    modules:
      - line-bot-llm.ApplicationKt.module
  deployment:
    port: 8080
    watch:
      - classes
      - resources
  development: $KTOR_DEVELOPMENT
line:
  channel_access_token: $LINE_CHANNEL_ACCESS_TOKEN
  room_id: $LINE_ROOM_ID
  channel:
    secret: $LINE_CHANNEL_SECRET
    token: $LINE_CHANNEL_TOKEN
cloudflare:
  account_id: $CLOUDFLARE_ACCOUND_ID
  access_token: $CLOUDFLARE_ACCESS_TOKEN
  llm:
    defalut_prompt: $LLM_DEFAULT_PROMPT
